name: CI/CD Pipeline for K3s

on:
  push:
    branches:
      - main # 當推送到主分支時觸發

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest

  deploy-to-machine:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client sshpass

      - name: Deploy to K3s
        env:
          K3S_IP: ${{ secrets.K3S_IP }} # K3s 虛擬機的 IP 地址
          K3S_USER: ${{ secrets.K3S_USER }} # 用於 SSH 的用戶名
          K3S_PASSWORD: ${{ secrets.K3S_PASSWORD }} # 用於 SSH 的密碼
          SSH_PORT: ${{ secrets.SSH_PORT }} # 自定義 SSH 端口號
        run: |
          sshpass -p "$K3S_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $K3S_USER@$K3S_IP << EOF
            # 使用 kubectl rollout restart 來重啟部署
            kubectl rollout restart deployment/my-deployment -n default

            # 等待滾動更新完成
            kubectl rollout status deployment/my-deployment -n default
          EOF
